name: Build and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Close Stale Issues
        uses: actions/stale@v4.1.1
